/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni.h>
#include <jni.h>
/* Header for class com_ao_diveroid_util_CvUtil */
#ifndef _Included_com_ao_diveroid_util_CvUtil
#define _Included_com_ao_diveroid_util_CvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ao_diveroid_util_CvUtil
 * Method:    filter
 * Signature: (J)J
 */
JNIEXPORT
jlong Java_com_diveroid_camera_utils_CvUtil_filter
( JNIEnv * env, jclass cls, jlong mat_addr, double level );

#ifdef __cplusplus
}
#endif
#endif